# GRANTED, DENIED, REVOKED consent
POST http://localhost:8181/context.json?sessionId={{context-Session-Id}}
Authorization: Basic karaf karaf
Content-Type: application/json

{
    "source":{
        "itemId":"homepage",
        "itemType":"page",
        "scope":"neosdemo"
    },
    "events": [
        {
            "scope":"neosdemo",
            "eventType":"modifyConsent",
            "source":{
                "itemType":"page",
                "scope":"neosdemo",
                "itemId":"anItemId"
            },
            "target":{
                "itemType":"anyType",
                "scope":"neosdemo",
                "itemId":"anyItemId"},
            "properties":{
                "consent":{
                    "typeIdentifier":"display ads",
                    "scope":"reka",
                    "status":"DENIED",
                    "statusDate":"2021-03-27T17:27:29.473Z",
                    "revokeDate":"2022-03-27T17:27:29.473Z"
                }
            }
        }
    ]
}

