Neos:
  Neos:
    fusion:
      autoInclude:
        'Hb180.DXP.Unomi': TRUE
  Fusion:
    defaultContext:
      Unomi.TrackingValues: Hb180\DXP\Unomi\Eel\Helper\TrackingValuesHelper
      Unomi.Yaml: Hb180\DXP\Unomi\Eel\Helper\YamlHelper
  Flow:
    mvc:
      routes:
        'Hb180.DXP.Unomi': TRUE
